drop table IF EXISTS drink;
drop table IF EXISTS user;

CREATE TABLE IF NOT EXISTS drink (
  DRINK_ID INT NOT NULL AUTO_INCREMENT,
  DRINK_NAME VARCHAR(128) NOT NULL,
  price INT NOT NULL,
  PRIMARY KEY (DRINK_ID),
  UNIQUE INDEX DRINK_ID_UNIQUE (DRINK_ID ASC));

CREATE TABLE IF NOT EXISTS user (
  USERNAME VARCHAR(128) NOT NULL,
  PASSWORD VARCHAR(128) NOT NULL,
  PRIMARY KEY (USERNAME),
  UNIQUE INDEX USER_NAME_UNIQUE (USERNAME ASC));